CREATE TABLE USERS
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	NAME VARCHAR(50)
)
DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;

INSERT INTO USERS (USERNAME, PASSWORD, NAME) VALUES ('bilal.kartal', '202cb962ac59075b964b07152d234b70', 'BİLAL KARTAL');

create TABLE PRODUCTS
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	UUID VARCHAR(32),
	PRODUCT_NAME VARCHAR(100)
)
DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;

create TABLE PRODUCT_OFFERS
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_PRODUCT INT,
	BRAND_NAME VARCHAR(100),
	COMPANY_NAME VARCHAR(100),
	CONTACT_NAME VARCHAR(100),
	CONTACT_PHONE VARCHAR(100),
	OFFER DECIMAL(15,2),
	COMMENT VARCHAR(1000)
)
DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;
